// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package datetimewithzones.actions;

import java.time.DateTimeException;
import java.time.ZoneId;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Return a boolean indicating if the timezone is valid.
 * 
 * Timezones are spelling and case sensitive, so this is a useful check to ensure the timezone is correct before using it in formatDateTime.
 */
public class isValidTimeZone extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String Timezone;

	public isValidTimeZone(IContext context, java.lang.String Timezone)
	{
		super(context);
		this.Timezone = Timezone;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			ZoneId zoneId = ZoneId.of(this.Timezone);
			return true;
		} catch (DateTimeException dte) {
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "isValidTimeZone";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
